# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/license.thirdoctopus.com
cert = /etc/letsencrypt/live/license.thirdoctopus.com/cert.pem
privkey = /etc/letsencrypt/live/license.thirdoctopus.com/privkey.pem
chain = /etc/letsencrypt/live/license.thirdoctopus.com/chain.pem
fullchain = /etc/letsencrypt/live/license.thirdoctopus.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 477049ee817434cf9ba2b5c27e9eb3f9
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
webroot_path = /opt/hrms-erp/nginx/html,
[[webroot_map]]
license.thirdoctopus.com = /opt/hrms-erp/nginx/html
