#!/usr/bin/env bash
# install.sh
# Brings up the OctoAssist Docker Compose stack.
# Idempotent — safe to re-run.
#
# Run from this directory:
#   cd /opt/octoassist/deploy/docker && sudo bash install.sh
#
# Generates random admin and DB passwords on first run, stores them in .env
# (mode 600). Subsequent runs reuse the same .env.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# --- Pre-flight ------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
  echo "Run as root (sudo bash install.sh)." >&2; exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker is not installed." >&2; exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' plugin is not installed." >&2; exit 1
fi

# --- .env: generate on first run, otherwise reuse --------------------------
ENV_FILE=".env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "==> Generating random credentials → $ENV_FILE"
  POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
  ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh on $(date -Iseconds)
# DO NOT commit this file.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$ADMIN_PASSWORD
TENANT_NAME=Third Octopus
EOF
  chmod 600 "$ENV_FILE"
else
  echo "==> Reusing existing $ENV_FILE"
fi

# --- Build & start ---------------------------------------------------------
echo "==> Building image"
docker compose build --quiet

echo "==> Starting stack"
docker compose up -d

# --- Wait for app health ---------------------------------------------------
echo "==> Waiting for app health on 127.0.0.1:8088"
HEALTHY=0
for i in $(seq 1 60); do
  if curl -fsS http://127.0.0.1:8088/health >/dev/null 2>&1; then
    HEALTHY=1; break
  fi
  sleep 2
done
if [[ "$HEALTHY" -ne 1 ]]; then
  echo "WARNING: app did not become healthy within ~120s. Check:" >&2
  echo "  docker compose logs --tail=80 app" >&2
fi

# --- Read enrolment key (bootstrapped by app startup) ----------------------
sleep 2  # tiny grace for the bootstrap commit
ENROL_KEY="$(docker exec octoassist-postgres psql -U octoassist -d octoassist -tAc \
  "SELECT enrolment_key FROM tenants ORDER BY id LIMIT 1;" 2>/dev/null | tr -d '[:space:]' || true)"

ADMIN_PASSWORD_PRINT="$(grep ^ADMIN_PASSWORD= "$ENV_FILE" | cut -d= -f2-)"

cat <<EOF

================================================================================
  OctoAssist (Docker) is running on this droplet.

  Internal URL (loopback only):
    http://127.0.0.1:8088/

  Admin:           admin
  Admin password:  $ADMIN_PASSWORD_PRINT
  Tenant:          Third Octopus
  Enrolment key:   ${ENROL_KEY:-<DB still bootstrapping — re-check in 30s>}

  Stored in:       $(pwd)/$ENV_FILE   (root-only, mode 600)

  Useful commands:
    docker compose ps
    docker compose logs -f app
    docker compose logs -f postgres
    docker compose restart app
    docker compose down            # stop + keep data volume
    docker compose down -v         # stop + DESTROY data volume

  NOT public yet — bound to 127.0.0.1:8088 only.
  To access from your laptop, open an SSH tunnel:

    ssh -i ~/.ssh/octoassist_deploy -L 8088:127.0.0.1:8088 root@68.183.246.16

  …then open http://localhost:8088 in a browser.

  WRITE DOWN THE ADMIN PASSWORD AND ENROLMENT KEY ABOVE — they will not be
  shown again. They live in $ENV_FILE.
================================================================================
EOF
