# sign-msi.ps1
# Signs the OctoAssistAgent.msi with the self-signed code-signing certificate
# generated by generate-cert.ps1.
#
# Prereqs:
#   - Windows SDK installed (provides signtool.exe)
#   - .\out\ThirdOctopus-CodeSigning.pfx exists
#
# Usage:
#   .\sign-msi.ps1 -MsiPath ..\dist\OctoAssistAgent.msi

param(
    [Parameter(Mandatory=$true)][string]$MsiPath,
    [string]$PfxPath = (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "out\ThirdOctopus-CodeSigning.pfx"),
    [string]$TimestampUrl = "http://timestamp.digicert.com"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $MsiPath)) { throw "MSI not found at $MsiPath" }
if (-not (Test-Path $PfxPath)) { throw "PFX not found at $PfxPath. Run generate-cert.ps1 first." }

$signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter "signtool.exe" -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -like "*\x64\signtool.exe" } |
    Sort-Object FullName -Descending |
    Select-Object -First 1

if (-not $signtool) {
    throw "signtool.exe not found. Install Windows 10/11 SDK from https://developer.microsoft.com/windows/downloads/windows-sdk/"
}

$PfxPassword = Read-Host -AsSecureString -Prompt "PFX password"
$plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($PfxPassword))

Write-Host "==> Signing $MsiPath"
& $signtool.FullName sign `
    /f $PfxPath `
    /p $plain `
    /tr $TimestampUrl `
    /td SHA256 `
    /fd SHA256 `
    /d "OctoAssist Asset Agent" `
    $MsiPath

Write-Host "==> Verifying"
& $signtool.FullName verify /pa /v $MsiPath

Write-Host "==> Done. Signed MSI: $MsiPath"
